site_name: SmartCLIDE Workflows jBPM
repo_url: https://github.com/eclipse-opensmartclide/kie-wb-common/tree/SmartCLIDE-addons

nav:
  - Getting Started: 'index.md'
  - Example 1: 'example1.md'
  - Example 2: 'example2.md'