name: Build

on:
  pull_request:
    branches:
      - SmartCLIDE-addons

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Docker Image
        run: |
          # login to GitHub Container Registry
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${GITHUB_ACTOR} --password-stdin
          # build image
          docker build . --tag ghcr.io/eclipse-opensmartclide/smartclide/jbpm:$(date +'%Y-%m-%d')