name: CI

on:
  push:
    branches:
      - SmartCLIDE-addons
  pull_request:
    branches:
      - SmartCLIDE-addons

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: SmartCLIDE-addons
      - name: Publish Docker Image
        run: |
          # login to GitHub Container Registry
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${GITHUB_ACTOR} --password-stdin
          # build image
          docker build . --tag ghcr.io/eclipse-researchlabs/smartclide/jbpm:$(date +'%Y-%m-%d')
          # push image
          docker push ghcr.io/eclipse-researchlabs/smartclide/jbpm:$(date +'%Y-%m-%d')